
services:
  - type: web
    name: avatar-training-backend-azure
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.app:app --host 0.0.0.0 --port 8000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: AZURE_SPEECH_KEY
        sync: false
      - key: AZURE_SPEECH_REGION
        value: japaneast
      - key: AZURE_SPEECH_VOICE
        value: ja-JP-NanamiNeural
    autoDeploy: true
